from __future__ import annotations

from PySide6.QtWidgets import QVBoxLayout
from PySide6.QtWidgets import QHBoxLayout
from PySide6.QtWidgets import QLabel
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import QDialog

class CreditsBox(QDialog):
    def __init__(self, parent, size_multiplier):
        super().__init__(parent)
        self.size_multiplier = size_multiplier

        credit_1_layout = QHBoxLayout()
        credit_1_label_image = QLabel()
        credit_1_label_image.setPixmap(QPixmap("Data\\profile1.png"))
        credit_1_label_image.setScaledContents(True)
        credit_1_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_1_layout.addWidget(credit_1_label_image)
        credit_1_label_text = QLabel()
        credit_1_label_text.setText("<span style=\"font-weight: bold; color: #67aeff;\">Lakifume</span><br/>Author of True Randomization<br/><a href=\"https://github.com/Lakifume\"><font face=Cambria color=#67aeff>Github</font></a>")
        credit_1_label_text.setOpenExternalLinks(True)
        credit_1_layout.addWidget(credit_1_label_text)
        credit_2_layout = QHBoxLayout()
        credit_2_label_image = QLabel()
        credit_2_label_image.setPixmap(QPixmap("Data\\profile2.png"))
        credit_2_label_image.setScaledContents(True)
        credit_2_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_2_layout.addWidget(credit_2_label_image)
        credit_2_label_text = QLabel()
        credit_2_label_text.setText("<span style=\"font-weight: bold; color: #e91e63;\">FatihG_</span><br/>Founder of Bloodstained Modding<br/><a href=\"http://discord.gg/b9XBH4f\"><font face=Cambria color=#e91e63>Discord</font></a>")
        credit_2_label_text.setOpenExternalLinks(True)
        credit_2_layout.addWidget(credit_2_label_text)
        credit_3_layout = QHBoxLayout()
        credit_3_label_image = QLabel()
        credit_3_label_image.setPixmap(QPixmap("Data\\profile3.png"))
        credit_3_label_image.setScaledContents(True)
        credit_3_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_3_layout.addWidget(credit_3_label_image)
        credit_3_label_text = QLabel()
        credit_3_label_text.setText("<span style=\"font-weight: bold; color: #e6b31a;\">Joneirik</span><br/>Datatable researcher<br/><a href=\"http://wiki.omf2097.com/doku.php?id=joneirik:bs:start\"><font face=Cambria color=#e6b31a>Wiki</font></a>")
        credit_3_label_text.setOpenExternalLinks(True)
        credit_3_layout.addWidget(credit_3_label_text)
        credit_4_layout = QHBoxLayout()
        credit_4_label_image = QLabel()
        credit_4_label_image.setPixmap(QPixmap("Data\\profile4.png"))
        credit_4_label_image.setScaledContents(True)
        credit_4_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_4_layout.addWidget(credit_4_label_image)
        credit_4_label_text = QLabel()
        credit_4_label_text.setText("<span style=\"font-weight: bold; color: #db1ee9;\">Atenfyr</span><br/>Creator of UAssetAPI<br/><a href=\"https://github.com/atenfyr/UAssetAPI\"><font face=Cambria color=#db1ee9>Github</font></a>")
        credit_4_label_text.setOpenExternalLinks(True)
        credit_4_layout.addWidget(credit_4_label_text)
        credit_5_layout = QHBoxLayout()
        credit_5_label_image = QLabel()
        credit_5_label_image.setPixmap(QPixmap("Data\\profile5.png"))
        credit_5_label_image.setScaledContents(True)
        credit_5_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_5_layout.addWidget(credit_5_label_image)
        credit_5_label_text = QLabel()
        credit_5_label_text.setText("<span style=\"font-weight: bold; color: #25c04e;\">Giwayume</span><br/>Creator of Bloodstained Level Editor<br/><a href=\"https://github.com/Giwayume/BloodstainedLevelEditor\"><font face=Cambria color=#25c04e>Github</font></a>")
        credit_5_label_text.setOpenExternalLinks(True)
        credit_5_layout.addWidget(credit_5_label_text)
        credit_6_layout = QHBoxLayout()
        credit_6_label_image = QLabel()
        credit_6_label_image.setPixmap(QPixmap("Data\\profile6.png"))
        credit_6_label_image.setScaledContents(True)
        credit_6_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_6_layout.addWidget(credit_6_label_image)
        credit_6_label_text = QLabel()
        credit_6_label_text.setText("<span style=\"font-weight: bold; color: #ffffff;\">Matyalatte</span><br/>Creator of UE4 DDS Tools<br/><a href=\"https://github.com/matyalatte/UE4-DDS-Tools\"><font face=Cambria color=#ffffff>Github</font></a>")
        credit_6_label_text.setOpenExternalLinks(True)
        credit_6_layout.addWidget(credit_6_label_text)
        credit_7_layout = QHBoxLayout()
        credit_7_label_image = QLabel()
        credit_7_label_image.setPixmap(QPixmap("Data\\profile7.png"))
        credit_7_label_image.setScaledContents(True)
        credit_7_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_7_layout.addWidget(credit_7_label_image)
        credit_7_label_text = QLabel()
        credit_7_label_text.setText("<span style=\"font-weight: bold; color: #7b9aff;\">Chrisaegrimm</span><br/>Testing and suffering<br/><a href=\"https://www.twitch.tv/chrisaegrimm\"><font face=Cambria color=#7b9aff>Twitch</font></a>")
        credit_7_label_text.setOpenExternalLinks(True)
        credit_7_layout.addWidget(credit_7_label_text)
        credit_8_layout = QHBoxLayout()
        credit_8_label_image = QLabel()
        credit_8_label_image.setPixmap(QPixmap("Data\\profile8.png"))
        credit_8_label_image.setScaledContents(True)
        credit_8_label_image.setFixedSize(int(self.size_multiplier*60), int(self.size_multiplier*60))
        credit_8_layout.addWidget(credit_8_label_image)
        credit_8_label_text = QLabel()
        credit_8_label_text.setText("<span style=\"font-weight: bold; color: #dd872e;\">Tourmi</span><br/>True Randomization Contributor<br/><a href=\"https://github.com/Tourmi\"><font face=Cambria color=#dd872e>Github</font></a>")
        credit_8_label_text.setOpenExternalLinks(True)
        credit_8_layout.addWidget(credit_8_label_text)
        credit_box_layout = QVBoxLayout()
        credit_box_layout.setSpacing(int(self.size_multiplier*10))
        credit_box_layout.addLayout(credit_1_layout)
        credit_box_layout.addLayout(credit_8_layout)
        credit_box_layout.addLayout(credit_4_layout)
        credit_box_layout.addLayout(credit_5_layout)
        credit_box_layout.addLayout(credit_6_layout)
        credit_box_layout.addLayout(credit_2_layout)
        credit_box_layout.addLayout(credit_3_layout)
        credit_box_layout.addLayout(credit_7_layout)

        self.setLayout(credit_box_layout)
        self.setWindowTitle("Credits")
        self.setFixedSize(0, 0)